sudo: required
language: node_js
node_js:
  - 8
addons:
    chrome: stable
before_script:
    - set -e
    - sudo chown root /opt/google/chrome/chrome-sandbox
    - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
    - yarn add @angular/cli
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

jobs:
    include:
        - stage: dependencies
        script: yarn install
