sudo: required
language: node_js
node_js:
  - 8
addons:
    chrome: stable
before_script:
    - set -e
    - sudo chown root /opt/google/chrome/chrome-sandbox
    - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
    - yarn add @angular/cli@1.7.1
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

jobs:
  include:
    - stage: test
      script:
        - yarn build:prod

before_deploy:
    - export PROJECT_DIR=`pwd`
    - cd /tmp
    - git clone https://github.com/itchef/app-runner.git installer
    - cd installer
    - cp -r $PROJECT_DIR/dist .
    - git add .
    - git commit -m "Added build package of cara app from $TRAVIS_BUILD_NUMBER [$TRAVIS_JOB_NUMBER]"

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: cara-staging-app
  on:
    branch: staging
