dist: precise
sudo: required
language: node_js
node_js:
  - 9.5.0

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
    - set -e
    - yarn add @angular/cli
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

jobs:
    include:
        - stage: dependencies
        script:
            - yarn install
        - stage: lint
        script:
            - yarn lint
        -stage: unit-tests
        script:
            - yarn test
        - stage: end-to-end
            - yarn e2e
        stage: build
        script:
            - yarn dev-build

notifications:
  email: false
