dist: precise
sudo: required
language: node_js
node_js:
  - 9.5.0

addons:
    chrome: stable
before_script:
    - set -e
    - yarn add @angular/cli
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
